export const filas = [
    {
        producto:"manzana",
        cantidad: 3,
        precio: 2.8,
        tienda: "Mercadona",
        notas: "Comprar 3 kilos",
        comprado: false,
        imagen: "messi.jpeg",
    },
    {
        producto:"naranja",
        cantidad: 4,
        precio: 1.2,
        tienda: "Mercadona",
        notas: "Comprar 1 bolsa",
        comprado: true,
        imagen: "messi.jpeg",
    },
    {
        producto:"pera",
        cantidad: 2,
        precio: 1.5,
        tienda: "Mercadona",
        notas: "Comprar 6",
        comprado: false,
        imagen: "messi.jpeg",
    },
    {
        producto:"uva",
        cantidad: 1,
        precio: 4.2,
        tienda: "Mercadona",
        notas: "Comprar 1 racimo",
        comprado: true,
        imagen: "messi.jpeg",
    },
    {
        producto:"plátano",
        cantidad: 3,
        precio: 0.5,
        tienda: "Mercadona",
        notas: "Comprar 3 kilos",
        comprado: false,
        imagen: "messi.jpeg",
    },
    {
        producto:"mango",
        cantidad: 2,
        precio: 2.99,
        tienda: "Mercadona",
        notas: "Comprar 2",
        comprado: true,
        imagen: "messi.jpeg",
    }
];